version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:sa-east-1:274201610284:task-definition/management-td:1"
        LoadBalancerInfo:
          ContainerName: "pension-management-container"
          ContainerPort: "9093"
        PlatformVersion: "LATEST"